### ISSUE TITLE
Feature request: Accessibility

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/design-system#1239]
Is it possible to include into the standard controls Alternative navigation and general accessibility features? potentially targeting the [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) standards? Allowing downstream products support all users if they adopt these components?

**Comment by MelSumner** [comment]
Hi Tristan, can you please explain more about the issue? Is there a specific component that you're having difficulty with? 

Thanks!

**Comment by tristanmorgan** [comment]
One example is for the table component I would like to use keyboard navigation to select a row (nomad jobs table for example) and follow the link to the job details.

I'm sorry, I'm not sure if the elements/components using in the web ui of the HashiCorp tools (Consul/Nomad/Vault) are using generic ember elements or Helios ones.

If I need to raise issues on specific projects please let me know and I'll close this one here.

**Comment by tristanmorgan** [comment]
Going by the description "interactive elements within cells will receive focus, but entire cells and entire rows will not." from the docs for table suggests it a case of the new helios element isn't in use yet.

[Table - accessibility](https://helios.hashicorp.design/components/table?tab=accessibility)
