### ISSUE TITLE
Synchronize CSS font-stack between DevDot and the design system

### ISSUE THREAD

**Issue by didoo** [hashicorp/design-system#128]
### Context

In [this Slack thread](https://hashicorp.slack.com/archives/C01KCU4HDPY/p1648222317499269?thread_ts=1648221234.435329&cid=C01KCU4HDPY) @ashleemboyer and @braydenlove have noticed that the CSS font-stacks for DevDot and HDS differ.

In CoreDevDotLayout ([link](https://github.com/hashicorp/dev-portal/blob/main/src/layouts/core-dev-dot-layout/core-dev-dot-layout.module.css#L6-L13)):
```
--font-body: system-ui, -apple-system, blinkmacsystemfont, 'Segoe UI', roboto, helvetica, arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
--font-display: system-ui, -apple-system, blinkmacsystemfont, 'Segoe UI', roboto, helvetica, arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
--font-monospace: ui-monospace, menlo, consolas, ubuntu mono, monospace;
```

In HDS tokens ([link](https://github.com/hashicorp/design-system/blob/main/packages/tokens/dist/devdot/css/tokens.css#L243-L245)):
```
--token-typography-font-stack-display: -apple-system, BlinkMacSystemFont, SF Pro Display, Segoe UI Display, Ubuntu, sans-serif;
--token-typography-font-stack-text: -apple-system, BlinkMacSystemFont, SF Pro Text, Segoe UI Text, Ubuntu, sans-serif;
--token-typography-font-stack-code: SF Mono, Consolas, Ubuntu Mono, monospace;
```

Discussing among us, we have decided it would be great to align them between the two codebases, so that DevDot can directly use the CSS variables/tokens provided by the design system

### Proposed solution

Below is a list of changes that I am proposing. 

#### Display/Text stack

- **`system-ui`** - **I am proposing not to add it** (so remove it from DevDot) - reason being is that it seems it may cause issues in some cases (apparently it caused issues in WebKit and Blink browsers with non-English languages, see [here](https://infinnie.github.io/blog/2017/systemui.html) and [here](https://markdotto.com/2018/02/07/github-system-fonts/) and [here](https://github.com/twbs/bootstrap/pull/22377)) - these are old issues, and we're not using non-English languages, but since it's just a replacement for `-apple-system` and `BlinkMacSystemFont` and we're already declaring it, there's no real need to add it
- **`-apple-system + BlinkMacSystemFont`** - in both DevDot and HDS, let's just leave them as they are
- **`SF Pro Display/Text`** - These are already in the HDS stack, I suggest we keep them so also DevDot will start to use them
- **`Segoe UI` vs `Segoe UI Display/Text`** - DevDot is using the first one, HDS the second one(s) - I could not find any reference to `Segoe UI Display/Text` online, probably it was me just looking at the design specs in Figma and using the description from there as font name, but is wrong (even the new variable font Segoe UI is just `Segoe UI` - so **I am proposing to change HDS to use `Segoe UI`** as in DevDot
- **`Roboto, Helvetica, Arial`** - they're not present in the HDS stack, so **I am proposing to add them to the HDS stack**
- **`Ubuntu`** - is not present in the DevDot stack, so **I am proposing to add it to the DevDot stack**
- **`Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol`** - I have not found many references online about why to add these, apart [from this article on CSS Tricks](https://css-tricks.com/snippets/css/system-font-stack/) - I suspect they're not needed anymore, but since they're pretty harmless in any case, **I propose to add them to the HDS stack**

#### Code stack

For the code stack things are much easier:
- **`ui-monospace`** - currently [the support is very low](https://caniuse.com/extended-system-fonts) so **I am proposing to remove it from DevDot** to simplify things
- **`SF Mono`** - this is missing from DevDot, so **I am proposing to add it to DevDot** 
- **`Menlo`** - this is missing from HDS, so **I am proposing to add it to HDS** 

/cc @heatherlarsen @braydenlove @cveigt + @ashleemboyer @hashicorp/design-systems what do you think?

**Comment by ashleemboyer** [comment]
This all sounds good to me! Thanks for all the research involved in figuring out these differences and which difference in the right one. 👏🏻 It sounds like after all updates are made to the HDS stack, DevDot will be able to just reference the relevant tokens? No additions or removals necessary on our part?

**Comment by didoo** [comment]
> This all sounds good to me! Thanks for all the research involved in figuring out these differences and which difference in the right one. 👏🏻 It sounds like after all updates are made to the HDS stack, DevDot will be able to just reference the relevant tokens? No additions or removals necessary on our part?

Yes, my expectation is that you can used directly one of these:

**design tokens**
```
--token-typography-font-stack-display
--token-typography-font-stack-text
--token-typography-font-stack-code

--token-typography-display-500-font-family
--token-typography-display-400-font-family
--token-typography-display-300-font-family
--token-typography-display-200-font-family
--token-typography-display-100-font-family
--token-typography-body-300-font-family
--token-typography-body-200-font-family
--token-typography-body-100-font-family
--token-typography-code-100-font-family
```

**helper classes**
```
.hds-font-family-sans-display
.hds-font-family-sans-text
.hds-font-family-mono-code

.hds-typography-display-500
.hds-typography-display-400
.hds-typography-display-300
.hds-typography-display-200
.hds-typography-display-100
.hds-typography-body-300
.hds-typography-body-200
.hds-typography-body-100
.hds-typography-code-100
```

I have opened the PR here: https://github.com/hashicorp/design-system/pull/136
