### ISSUE TITLE
Use relative units for width, height, and font size on FlightIcon SVGs

### ISSUE THREAD

**Issue by junyper** [hashicorp/design-system#13]
So that the icons can scale responsively when the browser is zoomed or the base font size is changed in browser settings, I propose that we:

1. set the width and height CSS styles on the `svg` element using relative units. e.g. `1rem` for the `small`/16px size and `1.5rem` for the `medium`/24px size  (or `1em`/`1.5em` if you want it to always scale with any adjacent text)
2. validate the size argument to ensure that it's a valid size.

Note: the `viewBox` attribute can (and should) still use pixels.

Here is the relevant WCAG guideline: https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html

**Comment by amyrlam** [comment]
Closing for now. Kind of ties into the issue with `rem` on our components, and is definitely something we should explore when tackle that issue.
