### ISSUE TITLE
Bug report: Top aligned tooltips render with minor space

### ISSUE THREAD

**Issue by marisachan** [hashicorp/design-system#1357]
Current behavior

Running Chrome Version 113.0.5672.92 (the latest) top aligned tooltips are rendering what looks to be a small space between the rectangle box of the tooltip and the triangle tip. This behavior was found in both Billing and Consul so I believe it may be an overall HDS bug. Screenshots attached! 

![Screenshot 2023-05-15 at 6 21 17 PM](https://github.com/hashicorp/design-system/assets/23002951/31dbd095-d97f-4dbb-a96f-7378d086662f)
![Screenshot 2023-05-15 at 7 51 26 PM](https://github.com/hashicorp/design-system/assets/23002951/70bb15bb-e67a-4039-b401-38e301a2ee8f)

SHOULD BE: Expected behavior
Tooltip should look seamless/connected when active.

## Steps to reproduce
Example 1: Consul
1. Dashboard
2. Consul
3. Services
4. Table header tooltip

Example 2: (Flex) Billing
1. Dashboard
2. Billing
3. Contracts
4. Contract Period
5. Support level tooltip

**Comment by alex-ju** [comment]
Hi @marisachan! Thank you for raising this, unfortunately I was not able to replicate the issue in 113.0.5672.92 just by replacing `{{tooltip}}` with `{{hds-tooltip}}` (see screenshot attached). Do you happen to have a branch where I can try to debug this?

<img width="1508" alt="Screenshot 2023-05-16 at 09 58 49" src="https://github.com/hashicorp/design-system/assets/788096/51d61504-aa15-4f24-9969-308395532f56">

**Comment by alex-ju** [comment]
Can you check if the page is not zoomed in or out (`⌘`+`0`), by any chance?

**Comment by didoo** [comment]
@alex-ju @marisachan by the look of if (in particular the border radius) it doesn't seem an HDS tooltip?

**Comment by marisachan** [comment]
Apologies for the late reply! Thanks for taking a look into this @alex-ju @didoo ! Christian I brought up the border radius to my dev partner and she let me know:

> Yeah I think the way to use the tooltip with a FlightIcon has changed since I last had to implement it - when you originally posted this I was looking for instances of a PDS tooltip which I couldn't find. The fix should be super easy!

So I think we have it figured out and my dev partner will go back and update it! Thanks for pointing that out Christian!
