### ISSUE TITLE
Warn users if they specify an icon that doesn't exist

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/design-system#14]
_If possible_
Given I am a consumer of the ember addon
And I do not specify an icon or the icon specified does not exist
I get a friendly error (or warning) notifying me that this needs to be corrected

**Comment by amyrlam** [comment]
Doing some issue housekeeping with the move to the monorepo. Closing as "won't do" for now. Hasn't been an issue with our consumers. But could definitely be brought up in the future
