### ISSUE TITLE
Flight website uses two CSS resets (Normalize + Tailwind)

### ISSUE THREAD

**Issue by didoo** [hashicorp/design-system#151]
While working on #150 I noticed in the generated CSS for the Flight website (`packages/flight-website/dist/assets/flight-website.css`) that it contains two resets: one from [Normalize](https://github.com/sindresorhus/modern-normalize) and one from [Tailwind](https://tailwindcss.com/). See [flight-website.css.zip](https://github.com/hashicorp/design-system/files/8388386/flight-website.css.zip) for the full CSS, while below a couple of screenshots show what I mean:
| Normalize | Tailwind |
| --- | --- |
| <img width="940" alt="screenshot_1229" src="https://user-images.githubusercontent.com/686239/161032750-efc33b69-ca77-4fd5-af51-af48f8a76a6a.png"> | <img width="1072" alt="screenshot_1230" src="https://user-images.githubusercontent.com/686239/161033034-a1b474ee-625a-46bc-8ba9-2cac77ec73d4.png"> |

We don't know what is the combined effect of these two. Maybe we should remove one of them? (probably _normalize_, since we're heavily relying on Tailwind on that website?)

/cc @MelSumner

**Comment by Dhaulagiri** [comment]
I think normalize predated our usage of tailwind so we should be able to remove it

**Comment by Dhaulagiri** [comment]
Upon further inspection, what you're seeing is part of the tailwind stack as Tailwind is built on top of `modern-normalize` per [these docs](https://tailwindcss.com/docs/preflight).

Based on that I'll close this issue but feel free to re-open if we should investigate this further.
