### ISSUE TITLE
Standardize integration tests declarations

### ISSUE THREAD

**Issue by didoo** [hashicorp/design-system#158]
Would be great to standardize the way we write the integration tests. 

Some things that may be improved/we have to decide:
- not clear how to test the existence of the element (at the moment we test that it has the right class name, is it correct?)
   - somewhere (Structure? CloudUI?) I have seen something like `test('it renders' ... assert.ok(component.renders)`
- in some cases we use `it should render` in others `it renders`
   - @amyrlam suggested to use the component name instead of `it`
- do we want spacing or not between the single tests (they're visually grouped using a `// GROUP` comment
- check that all the tests have
   - spacing
   - grouping
   - tests for text/content and for assertions (in the early tests maybe we didn't do)
- remove the `.dom(this.element.querySelector('.[class]'))` in favour of `.dom('.[class]')` (much simpler!)

/cc @hashicorp/design-systems

**Comment by amyrlam** [comment]
It doesn't seem like something that has to be standardized, but may evolve as more tests are written (then update tests you touch to improve them) but def up to you.
- If prefer not to use classes so less brittle, could use something like `data-test-hds-alert`, which is common in cloud-ui. 
  - But there may be a known issue with that addon, I have not investigated it recently: https://github.com/hashicorp/design-system/issues/26
  - See `data-test-` example here with `hooks`: https://guides.emberjs.com/release/testing/test-types/#toc_application-tests

**Comment by didoo** [comment]
Closing this one, was done time ago and now tests are more or less uniform enough.
