### ISSUE TITLE
Explore "mix and match" (composite) icons

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/design-system#17]
Maybe a spike / epic? Bringing from Slack to an issue for tracking purposes.

@natmegs is looking to add icons like these numbered hexagons to `cloud-ui` : 
![image](https://user-images.githubusercontent.com/1372946/130176446-928d62fc-ef12-40a3-a426-c151f6530552.png)

From @dizzyup: 

> I was thinking maybe we could come up with a stack-like component that composes the base icons with a text label (this way we could also keep the shadow from the designs easily)

![image](https://user-images.githubusercontent.com/1372946/130176554-41be2802-f66d-437c-9c47-339528435e2b.png)

My thought was: maybe this will be an extension of FlightIcon, something like an `isCustom` param.

**Comment by amyrlam** [comment]
With the move to the monorepo, doing some issue cleanup and closing this as a "won't do" for now.

**Comment by amyrlam** [comment]
@natmegs @jesdavpet Apologies for the lack of clear communication here. In the move to the monorepo, we decided to mass close many issues. Reopening the issue per the internal Slack thread https://hashicorp.slack.com/archives/C032SA56A3Z/p1647976857914919, with the caveat that it's not immediately on the roadmap to be worked on. 

Sounds like there are some other solutions in the meantime and can continue the convo on Slack and/or here!

**Comment by didoo** [comment]
For context, see also this https://hashicorp.slack.com/archives/C018TLKDB6W/p1648578058071369?thread_ts=1648576465.863309&cid=C018TLKDB6W that refences this https://cloud-ui-storybook-hashicorp.vercel.app/?path=/story/stepperform--stepper-form

**Comment by didoo** [comment]
New thread about stepper icons: https://hashicorp.slack.com/archives/C7KTUHNUS/p1655141330412519

**Comment by didoo** [comment]
Now that the `Hds::Stepper::Step::Indicator` is provided, we can close this issue.
