### ISSUE TITLE
Bug report: unable to smoothly use template registry

### ISSUE THREAD

**Issue by SemaLuna** [hashicorp/design-system#1801]
## IS: Current behavior
When trying to use the template-registry in the repo, I was not able to get it working without TS errors.

Version: `"@hashicorp/design-system-components": "^3.1.1"`

This is my code:
```
import type HdsComponentsRegistry from '@hashicorp/design-system-components/addon/template-registry';

declare module '@glint/environment-ember-loose/registry' {
  export default interface Registry extends HdsComponentsRegistry {}
}
``` 

These are the errors:
```
node_modules/@hashicorp/design-system-components/addon/template-registry.ts:6:42 - error TS2307: Cannot find module '@hashicorp/design-system-components/components/hds/button' or its corresponding type declarations.

6 import type HdsButtonIndexComponent from '@hashicorp/design-system-components/components/hds/button';
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@hashicorp/design-system-components/addon/template-registry.ts:7:47 - error TS2307: Cannot find module '@hashicorp/design-system-components/components/hds/interactive' or its corresponding type declarations.

7 import type HdsInteractiveIndexComponent from '@hashicorp/design-system-components/components/hds/interactive';
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## SHOULD BE: Expected behavior
It should be possible to utilize the template-registry that's being populated in this repo

## Possible solution
Potentially convert to a V2 Addon, or document the proper steps to make use of the existing registry

**Comment by alex-ju** [comment]
hi @SemaLuna! I will investigate this and get back to you in the next few days.

**Comment by SemaLuna** [comment]
@alex-ju no problem, thanks for checking it out

I was mostly wondering if it was a me-problem :)

**Comment by alex-ju** [comment]
> @alex-ju no problem, thanks for checking it out
> 
> I was mostly wondering if it was a me-problem :)

No, I don't think it is, your code looks correct. Sorry for the inconvenience caused, I hope to resolve it in the next month (by the end of this year).

**Comment by alex-ju** [comment]
Hi @SemaLuna! a quick update: we kept ourselves busy migrating the Ember addons in this monorepo to v2 format resulting in a considerable delay on the TypeScript front. we hope to pick up this work soon, but I will refrain from giving any timelines this time. I'll get back on this thread as soon as we have a PR to publish the definition files.

**Comment by SemaLuna** [comment]
@alex-ju  thanks for the update - and no worries!

**Comment by alex-ju** [comment]
This should be fixed now. We're using a similar import in our `showcase` (test) app and the type declarations (for a limited number of components at the moment) are available to consumers without resulting in any errors
