### ISSUE TITLE
Flight icon request: [government]

### ISSUE THREAD

**Issue by rayelder** [hashicorp/design-system#193]
**Outline the use case for the new icon.**
Specific request by PMM stakeholder. Needed to support new solutions and industries listing pages.

**Screenshots**
<img width="129" alt="icon" src="https://user-images.githubusercontent.com/963856/162129278-9e14ed61-8d2d-4334-8a66-63c3095b4c56.png">

**Figma**
Use case: [Solutions / industries listing pages](https://www.figma.com/file/z8kFeVSViW6zPDBOFWtCG7/Solution-%2F-Industry-Listing-Page?node-id=411%3A1234)
Figma branch: [re.add-government-icon](https://www.figma.com/file/MYiw4kiVpunIMMw0sBkE1t/branch/Vkg336v3udJU1QmhelcJMq/%E2%9C%8F%EF%B8%8F-Flight-Development?node-id=205%3A0)

**Comment by rayelder** [comment]
I added a few versions in the Figma branch. Tomorrow, I'll sync with the Creative Design team and finalize both sizes.

**Comment by rayelder** [comment]
@cveigt Once approved, how long does it take for the icon to be available in Figma and code?

**Comment by rayelder** [comment]
<img width="538" alt="flight-government-icon 2@2x" src="https://user-images.githubusercontent.com/963856/162270176-f229e390-4d46-4854-85c1-0f94ad8763a0.png">

[government icon](https://www.figma.com/file/MYiw4kiVpunIMMw0sBkE1t/branch/Vkg336v3udJU1QmhelcJMq/%E2%9C%8F%EF%B8%8F-Flight-Development?node-id=1870%3A14) has been approved by Creative Design team.

**Comment by cveigt** [comment]
@rayelder I've made some adjustments to the icon. Tagged you in [Figma](https://www.figma.com/file/MYiw4kiVpunIMMw0sBkE1t/branch/Vkg336v3udJU1QmhelcJMq/%E2%9C%8F%EF%B8%8F-Flight-Development?node-id=1300%3A1385).

**Comment by cveigt** [comment]
@rayelder and Violet Huang have given thumbs up on the final icon ([Figma file](https://www.figma.com/file/MYiw4kiVpunIMMw0sBkE1t/branch/Vkg336v3udJU1QmhelcJMq/%E2%9C%8F%EF%B8%8F-Flight-Development?node-id=205%3A0) for reference).

<img width="119" alt="Screen Shot 2022-04-13 at 1 50 53 AM" src="https://user-images.githubusercontent.com/2142312/163138371-f3bfe88d-26f3-4997-bf61-cbcf05237f9d.png">

@didoo we can add this one to Flight. I've published the Figma library already.

**Comment by Dhaulagiri** [comment]
@cveigt this was released in `@hashicorp/flight-icons` 2.3.0
