### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by MelSumner** [hashicorp/design-system#196]
For instances where design has requested animations, we should determine the approach to uniformly implement the animations. 

For example, in the dropdown component, design has requested an animation for the chevron: 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/4587451/162485058-303a74ba-9963-4ff9-9335-bbc25aaa3e00.png">

However, in the implementation, we're using a different icon based on open/closed state: 
<img width="597" alt="CleanShot 2022-04-08 at 11 47 08@2x" src="https://user-images.githubusercontent.com/4587451/162486240-705ce05f-8c55-4a3e-9f5c-11c06d073ff1.png">

We should determine how we should accommodate everyone's requirements in a consistent way.

**Comment by didoo** [comment]
Outdated. Closing the issue.
