### ISSUE TITLE
Flight icon request: Git Logo

### ISSUE THREAD

**Issue by hannahcunningham2023** [hashicorp/design-system#2036]
Hi DS team!! Hope y'all are well. 

I'd like to request an icon of the Git logo. Git is an integral part of the Packer ecosystem and we will be increasingly showing Git metadata in HCP Packer. We would love to have this icon to support the UI like we do with other tools in our customer's ecosystems like GitHub, BitBucket, GitLab, etc. Learn more about Git and see their logo [here](https://git-scm.com/).

Thanks!
Hannah

**Comment by didoo** [comment]
@hannahcunningham2023 can you please use this intake form to submit the request? (a copy&paste is OK)
https://hashicorp.atlassian.net/wiki/spaces/HDS/pages/2648080407/Helios+HDS+Support+Intake+Form
in this way we can track it correctly in our Jira backlog. thanks 🙏

**Comment by Dhaulagiri** [comment]
This was also submitted via Jira now
