### ISSUE TITLE
Flight icon request: log

### ISSUE THREAD

**Issue by juliezzhou** [hashicorp/design-system#224]
**Outline the use case for the new icon.**
In Nomad, the user usually needs to look at the log page under task level to identify issue and troubleshoot. The log page has both stdout and stderr options. The current log page looks like this
![Screen Shot 2022-04-15 at 3 48 24 PM](https://user-images.githubusercontent.com/90711359/163625511-c27d106a-3066-422a-8ec8-06dcbdf732d5.png)

However, one of the biggest pain point in the Nomad UI is that people have to click so many times to get to that page. So the idea is we can show a log icon in the allocation table, so people can get to the log page quickly. The new page looks like this
<img width="606" alt="Screen Shot 2022-04-15 at 3 52 02 PM" src="https://user-images.githubusercontent.com/90711359/163625815-8d96f74e-7b0b-402b-95cf-29df80084b76.png">

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
There are similar icons in the system like what I have in the screenshot, but the engineers think that is for "terminal". 
We also have an icon called "file-source", but it looks more like a file to me. 
I think if we can have something like the file-source with the paper in the back, just change the "<>" into something else, that will work.
I also searched log icon in google, a lot of them has "log" text in the icon, altho i don't know if we have it small, will it be legible 

**Figma**
[Add links to the relevant Figma files where this icon is used, if possible.](https://www.figma.com/file/fuoeNcjc8vZApzcAvyK0AL/UI-improvement?node-id=1306%3A122972)

So let me know if this is not clear enough, i am happy to brainstorm on the idea.

**Comment by evankerrigan** [comment]
🙏 _I just noticed this PR and hope y’all don’t mind me adding something here opportunistically_ 

----

I recognize that the “visual refresh” is outdated and is _not_ a reliable source of truth, but it does help provide an example of where a logs icon might also be used on HCP. If we end up using icons in either the side-navigation and/or the icon tile in the header area, we’ll likely need some way of referencing logs (I used [the `align-left` icon](https://flight-hashicorp.vercel.app/?query=align-left) that currently exists in Flight for these examples). 

<img width="293" alt="nav-logs@2x" src="https://user-images.githubusercontent.com/70760/165848756-7aa41d95-9e0a-4bcc-9a9b-78f5a8c53959.png">

<img width="855" alt="Screen Shot 2022-04-28 at 14 30 09" src="https://user-images.githubusercontent.com/70760/165849008-f047ae7c-97f9-4a50-889d-be78f6f72e2f.png">

**Comment by cveigt** [comment]
@juliezzhou, I started to work on this icon and got a couple of ideas I wanted to run by you 👇

<img width="926" alt="Frame 209" src="https://user-images.githubusercontent.com/2142312/166848808-ac67a041-caf8-4255-b5cc-90f9512db3c6.png">

I think the first one works well as an icon on a table or the left nav Evan shared, but I got the impression that you want to avoid angle brackets "<>" so I came up with option C, which seems more related to search but at the same time, that describes what users use logs for.

Here's how they look in context

![Frame 223](https://user-images.githubusercontent.com/2142312/166850057-e64b4f01-afb9-476f-a4dd-f79c54fcdc4d.png)

![Frame 222](https://user-images.githubusercontent.com/2142312/166850067-4e17be45-864e-4385-b099-e486a07fef0f.png)

Let me know what you think. Happy to explore more.

@evankerrigan, thanks for sharing that example; it was helpful.

**Comment by evankerrigan** [comment]
I’ll let @juliezzhou chime in for how these might work in Nomad, but I think that any of these would work in the HCP examples should we need them — thanks for exploring, @cveigt!

**Comment by juliezzhou** [comment]
@cveigt thanks for the exploration. I think option A works the best in this scenario. I don't think the search icon makes sense at least for Nomad logs. and I like how simple option A is to show the lines of code.

**Comment by cveigt** [comment]
Awesome! I have added it to the main file and should be available with the next release

<img width="133" alt="Screen Shot 2022-05-09 at 9 08 12 PM" src="https://user-images.githubusercontent.com/2142312/167540778-537f1b68-b4f7-41e9-b2fc-c250d381f59e.png">

@juliezzhou I'll let you know when it's ready to consume in Figma and the code library.
