### ISSUE TITLE
External request: Fix link to "Rich Tooltip vs. Tooltip" in docs for "Rich Tooltip" component

### ISSUE THREAD

**Issue by HeroicEric** [hashicorp/design-system#2370]
## Description of the problem

The link to "Rich Tooltip vs. Tooltip" in the docs for the "Rich Tooltip" component links to the `#rich-toolip-vs-tooltip` anchor at `/` (the Helios landing page) but should instead link to the `#rich-tooltip-vs-tooltip` anchor on the current page (https://helios.hashicorp.design/components/rich-tooltip).

## Possible suggested solution

I believe removing the leading `/` from the link should fix the issue.

I [opened a PR](https://github.com/hashicorp/design-system/pull/2369) that should fix this before I was aware of the CLA. I'd rather not enter into any kind of legal agreements just to fix this tiny issue but feel free to take a look at the PR :)

**Comment by majedelass** [comment]
Thank you for bringing this to our attention and opening the issue.

We just pushed the fix and is now pointing to the right place on the page 😃 - Have a wonderful day!
