### ISSUE TITLE
Add general usage information

### ISSUE THREAD

**Issue by MelSumner** [hashicorp/design-system#238]
One of the things we are missing from our documentation is what we intend to do with the design system. 

I'm seeing comments in support chat about how we don't provide an exact 1:1 for some things, and we are continually needing to explain how this is purposeful- there are outdated or non-compliant (not accessible) designs that we do not intend to support. But we should say this on the scrappy site somehow, even if we have an RFC for the design system, because that seems to be where folks are looking for the answers. 

As an alternative, It's possible that we need to add this section to each component page, instead. Maybe if we already know what previous "versions" of components we do not intend to support, we can have a section that explains this.

Either way, this will help us set expectations across the board and improve user support.

**Comment by didoo** [comment]
Closing this one, we will review the entire documentation content in the context of the new website.
