### ISSUE TITLE
Flight icon request: plugin

### ISSUE THREAD

**Issue by braydenlove** [hashicorp/design-system#241]
**Outline the use case for the new icon.**
We are needing a Plugins icon which will appear in dropdown menus and on cards. We are using icons next to main sections on DevDot (Plugins is one of a few) and want to create an identification pattern with our users.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
We are currently using `box` which isn't exactly right. I could see us using the box icon for things like packages or releases in the future and feel like plugins needs its own specific icon

**Describe alternatives you've considered.**
We considered `socket` but weren't sure if it was too on the nose. It is also just a play on words and might not be as memorable from a visual perspective. We could also have socket related content on DevDot in the future.

**Screenshots**
<img width="1440" alt="waypoint-docs1" src="https://user-images.githubusercontent.com/81585949/164781170-a57477cb-2cde-49a5-a911-6d455e7cf5fc.png">
<img width="1440" alt="waypoint-docs2" src="https://user-images.githubusercontent.com/81585949/164781174-60d5feb9-7c62-4f2b-ad76-b57d5616e9a3.png">
<img width="1440" alt="waypoint-docs3" src="https://user-images.githubusercontent.com/81585949/164781175-5192c3c1-3f62-4f00-84f2-b6ee895a7f10.png">

**Figma**
[Link](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Dev-Portal?node-id=8395%3A113819) to figma

**Additional context**
A few icons I like from other systems
<img width="1870" alt="Screen Shot 2022-04-22 at 1 27 19 PM" src="https://user-images.githubusercontent.com/81585949/164781399-33cd25b8-eeec-471e-8c94-d41a5b5c9033.png">
[link](https://heroicons.dev/?query=puz)
[link](https://icons.getbootstrap.com/icons/plugin/)
<img width="971" alt="image" src="https://user-images.githubusercontent.com/81585949/164781538-07059cca-af16-4983-ad4d-1bcf92a4ecb4.png">
[link](https://img.icons8.com/fluency-systems-regular/344/plugin.png)

**Comment by cveigt** [comment]
@braydenlove we will be adding this icon to the library in the next release.
Let us know if you have any questions or feedback

<img width="123" alt="Screen Shot 2022-05-27 at 4 12 53 PM" src="https://user-images.githubusercontent.com/2142312/170799210-b80577d6-ea6d-4c49-94e3-fc3740fd9ce2.png">

<img width="1439" alt="Screen Shot 2022-05-27 at 4 15 38 PM" src="https://user-images.githubusercontent.com/2142312/170799377-db5ea831-a721-4a09-b9d3-8b8719946a59.png">

**Comment by braydenlove** [comment]
@cveigt per usual this looks great. Thank you so much.
