### ISSUE TITLE
Design: indicate escape hatch?

### ISSUE THREAD

**Issue by MelSumner** [hashicorp/design-system#246]
In our components, there are some escape hatches we offer but we don't want them to become the status quo. Is there potentially some design we could consider that could indicate such? 

Maybe an icon? If so, which one? 

No matter what the solution, looking to @heatherlarsen and @cveigt for some thoughts on this one if possible!

**Comment by heatherlarsen** [comment]
@MelSumner Do you mean in the documentation or somewhere else?

**Comment by didoo** [comment]
@MelSumner do you think this is still an issue?
