### ISSUE TITLE
Flight icon request: [icon-name]

### ISSUE THREAD

**Issue by hcunningham97** [hashicorp/design-system#248]
**Outline the use case for the new icon.**
A clear and concise description of the icon you want added.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
A clear and concise description of what the problem is. Ex. I can't use X icon because [...]

**Describe alternatives you've considered.**
A clear and concise description of any alternatives you've considered.

**Screenshots**
Add screenshots of the icon in context, if possible.

**Figma**
Add links to the relevant Figma files where this icon is used, if possible.

**Additional context**
Add any other relevant context.

**Comment by cveigt** [comment]
@hcunningham97 I think you may have created this issue by mistake. I don't see any description in it.

I saw these two coming through this afternoon, which are the ones you mentioned during office hours.
https://github.com/hashicorp/design-system/issues/250
https://github.com/hashicorp/design-system/issues/249

**Comment by hcunningham97** [comment]
Oops, apologies, I did create it by mistake. I'll close it out. Thanks!
