### ISSUE TITLE
Flight icon request: Filled version of "clock" icon 

### ISSUE THREAD

**Issue by hcunningham97** [hashicorp/design-system#249]
**Outline the use case for the new icon.**
Looking to use a filled version of the "clock" icon. 

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
We have an outlined version of the clock icon but I'm looking to use it for a new status type in HCP Packer. Currently, all statuses in HCP are using filled icons, not outlined. I'd like to keep that consistency. 

**Describe alternatives you've considered.**
I'm currently using the outline version of the clock icon, and though it is not a major UX flaw, I'd like to keep consistency with all statuses in HCP by using filled icons. 

**Screenshots**
This is the status next to other existing statuses in HCP Packer
<img width="320" alt="Screen Shot 2022-04-26 at 6 36 39 PM" src="https://user-images.githubusercontent.com/89043540/165415176-fee99be8-aab4-4c3e-91a8-086dac36741c.png">

**Figma**
This is a WIP figma mock using the various statuses. 
https://www.figma.com/file/dfZjArJo2Hdq4iDPUOWnTt/Single-Level-Ancestry-Tracking?node-id=980%3A8156

**Additional context**
None

**Comment by hcunningham97** [comment]
No longer needed. Thanks.

**Comment by cveigt** [comment]
@hcunningham97 wanted to give you an update on this.

<img width="118" alt="Screen Shot 2022-06-03 at 4 28 29 PM" src="https://user-images.githubusercontent.com/2142312/171966535-c71800e6-9a7e-4970-b34c-56418a6a8234.png">

We will be adding this icon to the Figma and code libraries next week.

**Comment by Dhaulagiri** [comment]
This was released in `@hashicorp/flight-icons@2.6.0` 🎉
