### ISSUE TITLE
Dropdown: Visual differences between code and Figma

### ISSUE THREAD

**Issue by heatherlarsen** [hashicorp/design-system#258]
While reviewing the new Dropdown component, I came across a few visual differences between what was implemented and what is in [Figma](https://www.figma.com/file/noyY6dUMDYjmySpHcMjhkN/HDS-Product---Components?node-id=5633%3A16319) (internal resource). @didoo asked me to put these all in one issue since they're all likely related, but let me know if we need to break these up. Happy to adjust.

## Issue 1
An in-between active and focus style is being applied to the first ListItem by default when the menu is opened via a mouse click. A sub-issue here is that this style is also being retained on the first ListItem when the user moves the mouse over other ListItems.

### Results
| Chrome       | Safari |
| ----------- | ----------- |
| <img width="224" alt="chrome-mouse-style" src="https://user-images.githubusercontent.com/8553306/165665236-ded56b86-42bc-4d05-96af-3d041ef41b41.png">  <img width="230" alt="chrome-mouse-hover" src="https://user-images.githubusercontent.com/8553306/165804031-dbae20cb-7647-45c3-952e-d05fb4726ca2.png">    |  <img width="227" alt="safari-mouse" src="https://user-images.githubusercontent.com/8553306/165665596-66f9720d-faaf-4fbc-82ba-907c8a8f96f8.png"> <img width="233" alt="safari-hover" src="https://user-images.githubusercontent.com/8553306/165804359-edd8b57e-9d4b-408b-a3c3-4b9ba046d3a8.png"> |

### Expected
❓I know focus needs to automatically move to the first interactive ListItem when the menu is opened with the keyboard, but does focus need to be visible on the first interactive ListItem when the menu is opened with a mouse? I found [one article](https://www.sarasoueidan.com/blog/focus-indicators/) that mentions ways of not displaying focus states for mouse users. 

If focus **doesn't need** to be visible when the user clicks the toggle with a mouse, then the first Interactive ListItem should display in the `Default` style.
| Dropdown Opened      | User interacts with menu with a mouse |
| ----------- | ----------- |
| <img width="303" alt="default-list" src="https://user-images.githubusercontent.com/8553306/165664486-b138d9df-3169-4fb3-b7d1-0097e1b08912.png"> | <img width="213" alt="safari-active" src="https://user-images.githubusercontent.com/8553306/165804561-c0c5513b-b093-4a93-bb5b-380eff75ed24.png"> |

If focus **needs** to be visible when the user clicks the toggle with a mouse, then the first Interactive ListItem should display in the `Focus` style. But when the user interacts with the list with a mouse, focus should not remain on the first ListItem as it then feels confusing to know which ListItem will be triggered. 

| Dropdown Opened      | User interacts with menu with a mouse |
| ----------- | ----------- |
| <img width="311" alt="focus-list" src="https://user-images.githubusercontent.com/8553306/165664575-04e96e3c-9a91-4a61-b8c5-6701ed415ea3.png"> | <img width="213" alt="safari-active" src="https://user-images.githubusercontent.com/8553306/165804561-c0c5513b-b093-4a93-bb5b-380eff75ed24.png"> |

---

## Issue 2
Active state is displaying without the "indicator" when clicking on a ListItem. 

### Results
| Chrome      | Safari (correct) |
| ----------- | ----------- |
|  <img width="239" alt="chrome-active" src="https://user-images.githubusercontent.com/8553306/165803647-84ca7438-b4ef-4763-b19d-c8eb4f7b54c2.png">   | <img width="213" alt="safari-active" src="https://user-images.githubusercontent.com/8553306/165803527-e5c963eb-d4a2-46ed-8076-f92d069ba692.png"> |

### Expected
<img width="213" alt="safari-active" src="https://user-images.githubusercontent.com/8553306/165803527-e5c963eb-d4a2-46ed-8076-f92d069ba692.png">

---

## Issue 3
Focus state has minor styling issue; the foreground color used should be `--token-color-foreground-action-active` not `--token-color-foreground-primary`. This is happening in all browsers.

### Results
<img width="229" alt="chrome-keyboard-focus" src="https://user-images.githubusercontent.com/8553306/165806894-5e9eea3a-ceb5-4898-a8b9-6fcea8f587e2.png">

### Expected
<img width="311" alt="focus-list" src="https://user-images.githubusercontent.com/8553306/165806987-1827b56b-5c7f-4693-be88-c2bf85f9bbac.png">

**Comment by didoo** [comment]
Thanks @heatherlarsen for opening this issue (and with such detail, much appreciated).
I've created an Asana ticket for this: https://github.com/hashicorp/design-system/issues/258
Let's prioritize it at the next sprint planning session.
/cc @MelSumner @alex-ju

**Comment by didoo** [comment]
Fixed in #259, so closing this one.
