### ISSUE TITLE
ember-flight-icons data-test-* not being stripped in production

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/design-system#26]
For reasons unknown, data-test-* selectors are not being stripped for production usage of ember-flight-icons.

#### cloud-ui
<img width="487" alt="Screen Shot 2022-01-10 at 13 34 02" src="https://user-images.githubusercontent.com/1672302/148827664-24aaa7e4-a1ae-4e44-b4d5-0dcf0892aff8.png">

#### website docs in this repo
<img width="514" alt="Screen Shot 2022-01-10 at 13 33 31" src="https://user-images.githubusercontent.com/1672302/148827661-33f9f463-0a73-4f0b-ba54-0927ba9b7874.png">

**Comment by Dhaulagiri** [comment]
I pushed for this initially but with reflection I'm inclined to agree with @johncowen (and others). I think it would be relatively easy to undo this since I haven't gotten the impression that usage of the `data-test-` attribute we're providing is high (but we'd want to confirm)

**Comment by didoo** [comment]
the `Pds::Icon` and
