### ISSUE TITLE
Flight icon request: azure-vms, azure-aks

### ISSUE THREAD

**Issue by natmegs** [hashicorp/design-system#262]
**Outline the use case for the new icon.**
* Azure VMs logo
* Azure AKS logo

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
N/A

**Describe alternatives you've considered.**
N/A

**Screenshots**

**Figma**

**Additional context**
The official Microsoft logos are available for download [here](https://docs.microsoft.com/en-us/azure/architecture/icons/), within the download package the ones we're interested in can be found at:
* Azure VMs: `/Compute/10021-icon-service-Virtual-Machine.svg`
* AKS: `/Compute/10023-icon-service-Kubernetes-Services.svg`

**Comment by cveigt** [comment]
Posting an update here for visibility: We plan to add these icons to the library within the next couple of weeks or so. We'll let you all know when they are released so Consul can switch over the Flight version.
