### ISSUE TITLE
Bug report: CopyItem shows success state for multiple copied items simultaneously

### ISSUE THREAD

**Issue by noelledaley** [hashicorp/design-system#268]
## IS: Current behavior
When a dropdown has multiple `CopyItem`s, both items can appear copied at once:

https://user-images.githubusercontent.com/903288/166738940-8c215c3a-18de-42df-87d7-c0a6d61591d8.mov

## SHOULD BE: Expected behavior
Only one CopyItem should appear copied at a time.

## Steps to reproduce
1. Navigate to https://design-system-components-hashicorp.vercel.app/components/dropdown
2. Find the section for "ToggleButton + Title, Description, CopyItem, Separator"
3. Click to expand and open the example dropdown
4. Click to copy one item, and then the other
5. Notice you see the green copy icon (aka success state) for both 

## Possible solution
The dropdown should optionally be able to keep track of whether one of its child `CopyItem`s has been copied & clear the copied item when a new one is selected.

**Comment by MelSumner** [comment]
That's a good point; I'm resolving some other issues with this component & can include an update for this as well.
