### ISSUE TITLE
Docs: Add usage guidelines for animated icons

### ISSUE THREAD

**Issue by cveigt** [hashicorp/design-system#27]
Since we are adding animated icons, it'd be helpful to outline this new category and add some examples to the design guidelines.

### Updates: ###
- Add a new type under Available Types.
- Add a new item under best practices.

#### Copy updates: ####

- **Animated**
Glyph with animated effect, e.g. spinning
Used to show a transition between two states.
- **Use animated icons to communicate activity happening in the background**
For example, when an object is updated, the 'loading' icon could appear after the save or update action is triggered, indicating that the changes are in progress.

#### Screenshots ####
<img width="878" alt="Screen Shot 2022-01-17 at 10 50 36 AM" src="https://user-images.githubusercontent.com/2142312/149824228-2e8cb9a9-7c59-4180-bb5a-bc10a37046c2.png">

<img width="794" alt="Screen Shot 2022-01-17 at 10 52 10 AM" src="https://user-images.githubusercontent.com/2142312/149824267-83e297ba-8f3d-4d92-bc93-2d650d6f4b84.png">

I've made some scrappy GIFs, so we show them animated, not static.

![icon-types-animated](https://user-images.githubusercontent.com/2142312/149826309-7bcdaad8-503c-4b96-8d4b-59bbaab844d0.gif)

![icon-types-bp-animated](https://user-images.githubusercontent.com/2142312/149826177-4801f26d-44ff-4059-8fb4-373fc3652112.gif)

**Comment by didoo** [comment]
@cveigt it this still a valid issue? If yes, can you please move it to JIRA and close this one? Thanks

**Comment by cveigt** [comment]
@didoo I've created a Jira ticket: https://hashicorp.atlassian.net/browse/HDS-718
Closing this issue.
