### ISSUE TITLE
The "design tokens" documentation page is broken

### ISSUE THREAD

**Issue by didoo** [hashicorp/design-system#272]
https://design-system-components-hashicorp.vercel.app/foundations/tokens

<img width="1580" alt="screenshot_1409" src="https://user-images.githubusercontent.com/686239/166977278-bb03f0c5-4153-4929-b4b6-4ffc79b67a28.png">

`Ember is not defined` 🤷‍♂️

**Comment by MelSumner** [comment]
Looks like the whole site is broken for me right now. However, I'm very puzzled by this because if you look at the preview of the last merged change, everything is fine.

**Comment by Dhaulagiri** [comment]
The most likely explanation would be that one of the dependency changes in https://github.com/hashicorp/design-system/pull/265 had some unintended side effects. We could try reverting that and see if the preview app works as expected.

**Comment by Dhaulagiri** [comment]
<img width="1088" alt="Screen Shot 2022-05-05 at 12 50 06" src="https://user-images.githubusercontent.com/1672302/166982912-c2c5ee61-3280-49f9-bb3c-e1ea092001c2.png">

**Comment by Dhaulagiri** [comment]
See https://github.com/hashicorp/design-system/pull/273 for a fix
