### ISSUE TITLE
Review of focus management in Disclosure (+ Dropdown/Breadcrumb) components

### ISSUE THREAD

**Issue by didoo** [hashicorp/design-system#280]
@alex-ju as your first ticket, I would like you to review holistically the management of the `focus` in the `Disclosure` component (and therefore also in the `Dropdown` and `Breadcrumb` components, that use this generic component under the hood) and in the process fix a few issues/bugs that have been raised. 

Below I'll add as much information I have and context as possible, but please ask me or @MelSumner if there is something not clear. 

The general idea is that you could become the go-to person when comes to focus management in the HDS code library, in the long term :)

_Notice: I'll leave it to you how to organize/submit the PRs (single PR, multiple PRs, etc), no strong preferences._

## Known bugs and other possible issues

These are the bugs we know exist and we want to try to fix, and some other potential issues may be fixed/improved too.

### Fix "focus-trap" bug when the `interactive` opens a modal

There is a bug with the `focus-trap` when a modal is opened as result of one of the dropdown actions. See screen recording in the comment here: https://github.com/hashicorp/cloud-ui/pull/2362#issuecomment-1097778784
Not even sure how to debug/fix it, seems it's caused by the focus being returned to the dropdown list content when the modal is closed, but the dropdown content is not anymore there (but one can see it in the browser, so not sure this is the issue).

- existing Asana ticket: https://app.asana.com/0/1202008719910219/1202122650634732
- issue found while testing the Dropdown component in Cloud UI: https://github.com/hashicorp/cloud-ui/pull/2362#issuecomment-1097778784

_Notice: to test this particular bug in Cloud UI, you have to set up the Cloud UI repo, and then check out the branch I was using for testing. Since Cloud UI takes some time to compile, the development could be extremely slow (and painful). I suggest maybe first try to see if you can reproduce it in another way, locally in the dummy app, and use the Cloud UI only as last resort._

### Scrolling caused by focus returning to the previously active element

You can see the issue reported here: https://github.com/hashicorp/design-system/issues/267 and the comments/thread in it. I am not sure if there is a "solution" to it, if there is a better approach, or of this is how it should work. I'll leave it to you to investigate more on this subject (or maybe you already have an answer based on your previous experience).

### First item focused on dropdown open

This was fixed in https://github.com/hashicorp/design-system/pull/259 but the solution looks counterintuitive to me (the fix was to set `shouldSelfFocus=true` which to me does the contrary of what we wanted, so not sure why this fixed the problem).

### Make the focus-trap optional in the "Disclose" component

You can see an explanation of the "issue" here: https://github.com/hashicorp/design-system/issues/45
It's not an issue yet, per se, but it may be if the dropdown is used with a content that doesn't contain focusable elements, and I would prefer to avoid having to refactor the code to accommodate this use cases, when the Dropdown component (and all the other components using the `Disclosure`) have already been adopted in the production codebases.

_Notice: this may be not an issue anymore, now that we've removed the "focus on first item" setting for the `Disclosure` (I haven't re-tested with the new config)._

### Are there alternatives to what we are doing, the addons we're using?

At the moment we're using `ember-focus-trap` (https://github.com/josemarluedke/ember-focus-trap) which is a wrapper around `focus-trap` (https://github.com/focus-trap/focus-trap) to manage:
- the focus trapping (the focusing on tab is cycled inside the dropdown)
- the click outside (it closes the dropdown)
- the `esc` key event (it closes the dropdown)

A few questions I had in mind, and I share with you, do what you want of it:
- should we use the Vanilla JS solution instead of the Ember addon, if this doesn't work as expected or it's hard for us to customize for our needs?
- we have in house Ember addons that do almost exactly what we need (see  [`disclosure` component](https://github.com/hashicorp/consul/tree/main/ui/packages/consul-ui/app/components/disclosure)
  and [`{{aria-menu}}` modifier](https://consul-ui-staging-cjythooc7-hashicorp.vercel.app/ui/docs/modifiers/aria-menu) - [source code](https://github.com/hashicorp/consul/blob/main/ui/packages/consul-ui/app/modifiers/aria-menu.js) and [`{{on-outside}}` modifier](https://consul-ui-staging-cjythooc7-hashicorp.vercel.app/ui/docs/modifiers/on-outside) - [source code](https://github.com/hashicorp/consul/blob/main/ui/packages/consul-ui/app/modifiers/on-outside.js))

  - should we port some code/parts from these addons to improve our implementation? is there something there that we missed in our implementation?
  - or more in general, should we use directly these addons (potentially even port them in the HDS component base and expose them for everyone to use them?)

_Notice: if you want to know more about the Consul code sync with @johncowen, he knows everything about that code (almost certainly he has written it too)._

## Links that could come handy

- Original implementation of the `Disclosure` component (in the old repo)
  - https://github.com/hashicorp/design-system-components/pull/180
  - https://github.com/hashicorp/design-system-components/pull/178
- Tickets related to `Disclosure` or `focus` in general
  - https://github.com/hashicorp/design-system-components/pulls?q=is%3Apr+disclosure
  - https://github.com/hashicorp/design-system/pulls?q=is%3Apr+disclosure
  - https://github.com/hashicorp/design-system/pulls?q=is%3Apr+focus

**Asana ticket for this task**: https://app.asana.com/0/1202008719910219/1202253786016960

**Comment by alex-ju** [comment]
Thank you for sharing the context on this Cristiano and the related issues! Also thanks to Melanie for sharing her working document on this topic.

After reviewing the component I would like to suggest a slightly different approach to our disclosure component. I understand that conceptually the disclosed container was perceived as a modal, which is probably the reason for trying to adhere to the rules of a modal dialogue (such as trapping the focus). I propose we shift our perception and we see it as a disclosure element, a simple control whose sole purpose is to show and hide a container. By doing so, we don't need to trap the focus within the component, on the contrary we need to make sure it's not trapped and it flows throughout the page.

I took the liberty of coding this proposal in #284 (apologies in advance for any faux-pas on the Ember land – I'm still learning its internals so I'm very much open to suggestions for improvement), so we can have a taste of what would it work like and to be able to check it solves the two bugs mentioned above.

**Comment by alex-ju** [comment]
Addressed in #284
