### ISSUE TITLE
Move all the "integration" tests under the "unit" tests folder?

### ISSUE THREAD

**Issue by didoo** [hashicorp/design-system#281]
While discussing with @alex-ju, we were looking at how we do testing for our components, and we realized that probably our tests are not `integration` tests but `unit` tests.

What I am proposing to do is to:
- move these test under the `unit` folder
- in the process rename the `module('Integration | Component | hds/***` description to `module('Unit | Component | hds/***`) (a find and replace will do the trick)
- re-run all the tests to check that they still work

What do you think @MelSumner @Dhaulagiri + @hashicorp/design-systems ?

**Comment by alex-ju** [comment]
After researching this a bit yesterday, it seems to be [idiomatic to call these `integration` tests in Ember](https://guides.emberjs.com/release/testing/testing-components/) so I'm more inclined to follow the convention and rewire my thinking.

**Comment by Dhaulagiri** [comment]
Even though this is a bit confusing @alex-ju is correct here. You _could_ do what you're proposing as it would not actually impact the tests, but it would be counter to the default Ember approach which I think we'd want to avoid. Additionally, any time we use Ember's generators to generate a new component we'd have to always manually do this every time.

A key nuance between "unit" tests and "integration" tests in ember is that unit tests don't require the Ember app to be running and are generally much simpler/focused on testing small functions within the app.

**Comment by didoo** [comment]
All clear. Closing the issue then. Thanks for the feedback!
