### ISSUE TITLE
Flight icon request: Peer

### ISSUE THREAD

**Issue by jnwright** [hashicorp/design-system#286]
**Outline the use case for the new icon.**
A new Peer entity is being added to Consul. It represents a Datacenter + Admin Partition pair.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
We'd like something that's similar to icons we already use for Admin Partitions and Datacenter to show that it's a related entity, and I don't think we have any kind of combination icon like that.

**Describe alternatives you've considered.**
Currently using the network-alt icon

**Screenshots**
![image](https://user-images.githubusercontent.com/16551527/168191181-e0042aeb-ac3a-49a4-83af-ca80320cd397.png)
The first row shows a service imported from the billing-app Peer, while the second row shows a service from the billing-app Partition

**Figma**
[Cluster Peering](https://www.figma.com/file/nEhxeDU1hm5eqEPcU4Y1QT/Cluster-Peering?node-id=4058%3A13005)

**Additional context**
We use the organization icon for Datacenter
![image](https://user-images.githubusercontent.com/16551527/168191563-6c637e91-a5d0-4b1c-a13e-1f5cb3a678f4.png)

[WIP icon](https://www.figma.com/file/MYiw4kiVpunIMMw0sBkE1t/branch/hXuJ1fMV2auJc3VsJTsWVw/%E2%9C%8F%EF%B8%8F-Flight-Development?node-id=205%3A0)

**Comment by cveigt** [comment]
@jnwright could you confirm if this icon is still needed? You mentioned that this request might need to get updated with new information.

**Comment by cveigt** [comment]
Closing this request as the icon is no longer needed.
