### ISSUE TITLE
Bug report: "navigator.clipboard.readText is not a function" in Firefox

### ISSUE THREAD

**Issue by didoo** [hashicorp/design-system#290]
## IS: Current behavior
When clicking on the `CopyItem` in Firefox, a javascript error occurs:
<img width="1792" alt="screenshot_1445" src="https://user-images.githubusercontent.com/686239/168259747-57b8dfaf-3b62-4840-9449-4a8f583967b0.png">

## SHOULD BE: Expected behavior
It should copy the value

## Steps to reproduce
1. Visit https://design-system-components-hashicorp.vercel.app/components/dropdown in Firefox
2. Open the "console" panel in the dev tools
3. Go to the example "Integrate with Terraform Cloud"
4. Click on "Endpoint URL"
5. You will see the error: `navigator.clipboard.readText is not a function`

## Possible solution
A [quick search on StackOverflow](https://stackoverflow.com/questions/67440036/navigator-clipboard-readtext-is-not-working-in-js) seems to indicate that [Firefox doesn't allow the reading of the clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText#browser_compatibility), so maybe we should add a `guard` that checks if the function exists, otherwise assume the `write` was successful.

**Comment by MelSumner** [comment]
I checked that all browsers supported this before implementing, seems like I missed something somewhere. I'll go back through and figure it out and submit a patch for this issue.

**Comment by MelSumner** [comment]
Update: this fell through the cracks so I'm working on it again, apologies. 

This is from the documentation: 

> However, while [navigator.clipboard.readText()](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText) and [navigator.clipboard.writeText()](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText) work on all browsers, [navigator.clipboard.read()](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read) and [navigator.clipboard.write()](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write) do not. For example, on Firefox at the time of writing, [navigator.clipboard.read()](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read) and [navigator.clipboard.write()](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write) are not fully implemented

Now, this is a bit confusing, since I did use writeText and readText here. However, I'll add guards as you've suggested and make the solution more robust.
