### ISSUE TITLE
Flight icon request: Filled minus-square

### ISSUE THREAD

**Issue by hcunningham97** [hashicorp/design-system#294]
Outline the use case for the new icon.
Looking to use a filled version of the "minus-square" icon.

If there's a similar existing icon, why isn't it a good fit? Please describe.
We have an outlined version of the minus-square icon but I'm looking to use it for a new status type in HCP Packer. Currently, all statuses in HCP are using filled icons, not outlined. I'd like to keep that consistency.

Describe alternatives you've considered.
I'm currently using the outline version of the minus square icon, and though it is not a major UX flaw, I'd like to keep consistency with all statuses in HCP by using filled icons.

Screenshots
This is the status next to other existing statuses in HCP Packer
![Screen Shot 2022-05-18 at 10 44 46 AM](https://user-images.githubusercontent.com/89043540/169097231-89331d4f-fdb9-4ed3-8583-3bc3c111830b.png)

Figma
This is a WIP figma mock using the various statuses.
https://www.figma.com/file/dfZjArJo2Hdq4iDPUOWnTt/Single-Level-Ancestry-Tracking?node-id=980%3A8156

Additional context
None

**Comment by cveigt** [comment]
@hcunningham97 We will be adding this icon to the Figma and code libraries next week.

<img width="121" alt="Screen Shot 2022-06-03 at 4 29 53 PM" src="https://user-images.githubusercontent.com/2142312/171966615-879db957-24a8-4550-8581-bc7dc5ccb707.png">

**Comment by cveigt** [comment]
@hcunningham97, heads-up: this icon will be added to the next release of Flight icons.

<img width="128" alt="Screen Shot 2022-06-06 at 9 36 32 AM" src="https://user-images.githubusercontent.com/2142312/172205096-28cc8c7d-6223-4875-abb2-f8e875018b20.png">

We'll let you know once it's available in the Figma and code libraries.
