### ISSUE TITLE
Flight icon request: [icon-name]

### ISSUE THREAD

**Issue by braydenlove** [hashicorp/design-system#36]
**Outline the use case for the new icon.**
We need a check/success icon that matches the sizing and balance of the dot icons (dot/dot-half). These icons will show up together inline in a sidebar to show progress within a collection. Currently we are using a larger check icon on Learn but with the new design system it feels odd due to the smaller typography and spacing we are using.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
check-circle-fill but drawn at the same size as dot and dot-half.

**Describe alternatives you've considered.**
I have considered using check-circle-fill but it feels too large in comparison to the dot icons.

**Screenshots**
<img width="404" alt="image" src="https://user-images.githubusercontent.com/81585949/157292335-00f71b7f-70a6-4a1a-81e3-ef5ebe3a109f.png">
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/81585949/157295101-a7f9e24f-bb2d-44ff-b788-0a773480b259.png">

**Figma**
[Add links to the relevant Figma files where this icon is used, if possible.](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Dev-Portal?node-id=6297%3A71279)

**Additional context**
Let me know if you have any other questions!

**Comment by didoo** [comment]
@braydenlove maybe I'm missing something, but why `circle-fill` and `circle-half` would not work? (I mean, replace the "dot" with the "circle" ones, and scale them down to the size you need).

**Comment by braydenlove** [comment]
Are we able to go smaller than 16px? I was trying to keep them at the standard sizes 16 or 24px. Using the circles at 16px still feels like overkill and fights with the typography which should be the main focus.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/81585949/157298429-2218e377-7dde-4801-8f24-b2f41af42060.png">

**Comment by didoo** [comment]
> Are we able to go smaller than 16px?

We've gone below 16px in a lot of places already ;)

**Comment by braydenlove** [comment]
Awesome, feel free to close this then!

**Comment by didoo** [comment]
As discussed with @braydenlove he can use the existing "circle" icons, so we can close this one.

/cc @cveigt

**Comment by braydenlove** [comment]
Thanks @didoo
