### ISSUE TITLE
Flight icon request: [closed-caption]

### ISSUE THREAD

**Issue by braydenlove** [hashicorp/design-system#37]
**Outline the use case for the new icon.**
We have a closed caption icon our video player. For DevDot we would like to replace the icons used on the existing player in order to be more consistent. We have everything we need except for a closed caption icon. Happy to use something else if you have other suggestions.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
Nothing really similar, we could house the CC options in the settings icon but I am not sure how much control we have. It would also require a bit of discovery work for users in order to find the CC controls.

**Describe alternatives you've considered.**
A button could work but would increase the height of the control bar.

**Screenshots**
<img width="915" alt="image" src="https://user-images.githubusercontent.com/81585949/157300351-a64bbad0-164c-465b-979e-98c201244f5c.png">

**Figma**
[Add links to the relevant Figma files where this icon is used, if possible.](https://www.figma.com/file/VD7ahvXuXWJApeGnhbW4hv/Dev-Portal?node-id=6297%3A71283)

[Page with Learn's video player](https://learn-9qu12105v-hashicorp.vercel.app/tutorials/terraform/infrastructure-as-code?in=terraform/aws-get-started)

**Additional context**
N/A

**Comment by cveigt** [comment]
@braydenlove, thanks for the submission. I'll reach out for more details if needed.

**Comment by cveigt** [comment]
@braydenlove what do you think about this icon?
<img width="122" alt="Screen Shot 2022-03-28 at 1 30 10 AM" src="https://user-images.githubusercontent.com/2142312/160358747-f9712b12-772d-419b-aa57-22b91dd2d689.png">

Here's how it looks next to the others you might use for the player controls.
<img width="213" alt="Screen Shot 2022-03-28 at 1 32 04 AM" src="https://user-images.githubusercontent.com/2142312/160359052-c30ee6ab-5af0-416a-90b7-e8a99c995891.png">
