### ISSUE TITLE
Flight icon request: HCP

### ISSUE THREAD

**Issue by priscilasr** [hashicorp/design-system#370]
**Outline the use case for the new icon.**
I am looking for the HCP icon. It is a provider icon used in the registry modules page.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
There is not a similar existing icon.

**Describe alternatives you've considered.**
N/A

**Screenshots**
<img width="128" alt="Screen Shot 2022-06-13 at 11 26 45 AM" src="https://user-images.githubusercontent.com/44178960/173400455-b3192b7f-397a-48e0-ade3-a4cc8cda476b.png">
<img width="353" alt="Screen Shot 2022-06-13 at 11 40 41 AM" src="https://user-images.githubusercontent.com/44178960/173403312-9c7ed771-25ec-41b7-b262-589e3d198dca.png">

**Figma**
N/A

**Additional context**
<img width="1361" alt="Screen Shot 2022-06-13 at 11 41 43 AM" src="https://user-images.githubusercontent.com/44178960/173403323-24c4d87b-3463-48e7-82c4-348622027de0.png">

**Comment by heatherlarsen** [comment]
Hi @priscilasr, please use the existing HCP icon found here: https://flight-hashicorp.vercel.app/?query=hcp

Thanks!
