### ISSUE TITLE
Look into suggestions about `optional`, `unique-id` and other helpers for form controls

### ISSUE THREAD

**Issue by didoo** [hashicorp/design-system#384]
As suggested by @johncowen in https://github.com/hashicorp/design-system/issues/383#issuecomment-1158964831

> I would hazard a guess that we all use it already, and if you specify a pretty loose dependency so you don't step on toes, we should all be fine.
>
> `optional` is available from v1 and above, so you would be good even with `*`, it's unlikely they'll ever remove it.
>
> Using it instead would remove a tonne of repetitive code you have here that is only going to increase if you don't want to pull this dep in.
>
>---
> Maybe lookup `unique-id` aswell, which would help you here, it's in ember-core now.
>
> In case you are interested, we also have a `class-map` helper which is modelled on [`lit`s](https://lit.dev/docs/templates/directives/#classmap) (usage in [Shoelace](https://github.com/shoelace-style/shoelace/blob/next/src/components/button/button.ts#L166-L190)) which would also reduce a lot of the repetitive stuff. Keeps the string names front and center in the template and can easily be used on multiple HTML nodes within a single template without having to write loads of corresponding JS class methods just to switch classes in and out.
> We use it as one liner boolean switches to add lots of conditional classes:
> https://consul-ui-staging-gohp4f23a-hashicorp.vercel.app/ui/docs/helpers/class-map
>
> I can see you do that stuff a lot ^
>Hope it helps!

**Comment by MelSumner** [comment]
Since `{{unique-id}}` didn't ship until v4.4, we'd need to wait for that one. I am very excited for us to get to use it, though!!

**Comment by johncowen** [comment]
There's a polyfill in the meantime (https://github.com/ctjhoa/ember-unique-id-helper-polyfill). We will drop our custom one as and when we get there (https://github.com/hashicorp/consul/blob/main/ui/packages/consul-ui/app/helpers/unique-id.js) and you could do the same but with `guidFor` in a few lines if you didn't want to depend on that. Seeing as its now 'reserved' as long as you kept the same functionality interface you'd be fine.

**Comment by didoo** [comment]
Closing this as stale
