### ISSUE TITLE
Flight icons request: Several brand logos

### ISSUE THREAD

**Issue by evankerrigan** [hashicorp/design-system#405]
### Outline the use case for the new icon
The Cloud Visibility team is working on a feature where users can stream audit logs to third-party observability platforms. As part of the set up flow, users will need to indicate which third-party service they’re using as well as the necessary configuration values needed by that particular service. To help users more easily identify the service they’re seeking, we’re looking to add the corresponding brand logos for each choice. We’ve identified the following services as ones to roll out in the near future:

- AWS CloudWatch
- AWS S3
- Azure Blob Storage
- Datadog
- Grafana Cloud
- Splunk Cloud

### If there’s a similar existing icon, why isn’t it a good fit? Please describe.
N/A

### Describe alternatives you’ve considered.
N/A

### Screenshots
<img width="1440" alt="log-streaming" src="https://user-images.githubusercontent.com/70760/175407673-a65f17a5-685b-4c9d-b2ad-7d70252b17b0.png">

### Figma
[Visibility - Audit log streaming](https://www.figma.com/file/k08dy2DBhWhXl0LgOAzAu4/Visibility-Audit-logs-streaming)

### Additional context
We won’t need all of these logos available at the same time.

#### First priority

- AWS CloudWatch
- Datadog

#### Can come later

- AWS S3
- Azure Blob Storage
- Grafana Cloud
- Splunk Cloud

**Comment by cveigt** [comment]
Posting here for visibility: We plan to add these icons to the library within the next couple of weeks. We'll let you know when they are released. @evankerrigan mentioned that the pages where these icons will be used haven't been implemented or are still under development, so hopefully, they will be able to use the Flight version of the icons when we release them.
