### ISSUE TITLE
Bug report: alert-diamond icon doesn't show up inside Hds::Alert

### ISSUE THREAD

**Issue by noelledaley** [hashicorp/design-system#407]
## IS: Current behavior

When using `<Hds::Alert @color='critical' />`, the `alert-diamond` icon does not show up by default. It also does not show up if we explicitly pass in `@icon='alert-diamond'`. Other icons work if we explicitly pass them in. 

![Screen Shot 2022-06-24 at 11 25 44 AM](https://user-images.githubusercontent.com/903288/175640775-85c38e96-538a-46c7-8f57-37ff0d0dab94.png)
## SHOULD BE: Expected behavior
`<Hds::Alert @color='critical' />` should render the `alert-diamond` by default.

## Steps to reproduce
1. See code snipped in screenshot above!

**Comment by alex-ju** [comment]
Hi @noelledaley! 👋  Thank you for reporting this! Could you please try bumping `@hashicorp/ember-flight-icons` (`2.0.8` seems to be the latest version) – I'm suspecting `vault` in `cloud-ui` may be using a version before the `alert-diamond`. Otherwise let me know and I'll investigate further.

**Comment by MooCohen** [comment]
> Hi @noelledaley! 👋 Thank you for reporting this! Could you please try bumping `@hashicorp/ember-flight-icons` (`2.0.8` seems to be the latest version) – I'm suspecting `vault` or `hcp` may be using a version before the `alert-diamond` icon was added. Otherwise let me know and I'll investigate further.

Hi @alex-ju ! I just tried updating (locally) vault and core with `^2.0.8` and ran a fresh `yarn`.  The `alert-diamond` icon still didn't show in `@type=critical` `Hds::Alert` 's, even when specified.  For a fill-in we're passing in the `alert-octagon`

**Comment by alex-ju** [comment]
> > Hi @noelledaley! 👋 Thank you for reporting this! Could you please try bumping `@hashicorp/ember-flight-icons` (`2.0.8` seems to be the latest version) – I'm suspecting `vault` or `hcp` may be using a version before the `alert-diamond` icon was added. Otherwise let me know and I'll investigate further.
> 
> Hi @alex-ju ! I just tried updating (locally) vault and core with `^2.0.8` and ran a fresh `yarn`. The `alert-diamond` icon still didn't show in `@type=critical` `Hds::Alert` 's, even when specified. For a fill-in we're passing in the `alert-octagon`

Hey @MooCohen! I think what you're encountering is a dependency resolution issue. I've just started to get myself familiarised with `cloud-ui`, but updating `@hashicorp/ember-flight-icons` to `2.0.8` in [hcp](https://github.com/hashicorp/cloud-ui/blob/master/hcp/package.json#L147) (as well as in `vault`, but I see you've already done that) fixes your issue and the `alert-diamond` icon renders as expected. Would you be willing to give this a go?

**Comment by didoo** [comment]
@MooCohen @noelledaley is better to update the dependency on the whole Cloud UI codebase, to avoid misalignment between engines (we're trying to keep parity of version between engines exactly for this reason, to avoid cases in which something doesn't work and is not clear why, and often the reason is a misalignment of versions between engines)
if you run this command in the root of the project it should update the icons package version across all the engines:
`yarn upgrade @hashicorp/ember-flight-icons` and it should work (I had the same issue in this ticket too: https://github.com/hashicorp/cloud-ui/pull/2898/commits/0c1633d1b43d8b00a466fa606cb88a42cc0487ed)
