### ISSUE TITLE
Research: lint fix in CI

### ISSUE THREAD

**Issue by MelSumner** [hashicorp/design-system#44]
I'd like to be able to suggest a change to grammar or spelling in the GitHub UI and not face linter issues.

We should research if there's a way to run lint:hbs --fix in the CI process so I don't have to pull down locally for tiny changes.

This is only a nice-to-have.

**Comment by Dhaulagiri** [comment]
In the interest of tidyness I'm going to "icebox" this and close it to keep the list of open issues more focused on things that we are likely to prioritize.
