### ISSUE TITLE
Flight icon request: Minus circle fill

### ISSUE THREAD

**Issue by Ashtronaut09** [hashicorp/design-system#451]
![image](https://user-images.githubusercontent.com/13004940/179235490-7d330a43-be52-44bc-ad6b-225c0b7ce2ca.png)
Just to align with other icons I'm using in my mock.

**Comment by cveigt** [comment]
@Ashtronaut09 could you use the outline (non-fill) version of the icons? See usage guidelines on the [docs](https://flight-hashicorp.vercel.app/design#available-types).
