### ISSUE TITLE
Bug report: IconTile border missing

### ISSUE THREAD

**Issue by heatherlarsen** [hashicorp/design-system#463]
## IS: Current behavior
When looking at the dashboard, I noticed some of the IconTile's look like they're missing their border. Upon further inspection, the border is being set to `1px solid transparent` in the CSS.

<img width="472" alt="Screen Shot 2022-07-18 at 3 36 24 PM" src="https://user-images.githubusercontent.com/8553306/179628849-3a3354f1-75d8-40a5-9a0b-d4894dbe14f3.png">

## SHOULD BE: Expected behavior
Expected behavior is that the border should be `1px solid var(--token-color-border-primary)`

## Steps to reproduce

1. Navigate to the [HCP dashboard](https://portal.cloud.hashicorp.com/orgs/c0537841-2ca8-449b-8f23-67903e083fb7/projects/736ebc6e-22ec-433b-9e9b-c0a3f28712c2), specifically in the 'ds-whats-live-in-prod' organization space
2. Observe IconTiles used in the product cards.

**Comment by didoo** [comment]
See thread here: https://hashicorp.slack.com/archives/CPB8GS9QT/p1658220312956889
