### ISSUE TITLE
Bug report: using documented `@color='error'` in `<Hds::Badge>` throws an assertion

### ISSUE THREAD

**Issue by jesdavpet** [hashicorp/design-system#471]
## Current behaviour

Using the documented argument value of `@color='error'` makes the `<Hds::Badge>` component mad. 😡

<img width="1375" alt="Screen Shot 2022-07-20 at 19 46 03" src="https://user-images.githubusercontent.com/5464587/180101460-057fa9fb-4141-4b85-b39d-3bc3cdc90c54.png">

## Expected behaviour

Either using the documented `@color='error'` should work, OR the [HDS Badge docs](https://design-system-components-hashicorp.vercel.app/components/badge) should reflect the actual supported values for `@color`. _(In this case, perhaps `critical` instead of ~`error`~?)_

<img width="1416" alt="Screen Shot 2022-07-20 at 19 44 51" src="https://user-images.githubusercontent.com/5464587/180101560-b5dd5846-24b0-4d93-a7e4-adf6b891938a.png">

## Steps to reproduce

1. Render an `<Hds::Badge ...>` with a `@color='error'`
2. 💥 

## Possible solution

🌈 ✨ _Follow your heart ... !!!_ 🕊️ ❤️

**Comment by didoo** [comment]
@jesdavpet thanks for reporting! 🙏 💜

It's an error in the documentation (probably at the beginning the color name was `error` and later was changed to `critical` but that one was missed).

Will be fixed in https://github.com/hashicorp/design-system/pull/472
