### ISSUE TITLE
Flight icon request: [Pipeline and Step]

### ISSUE THREAD

**Issue by cveigt** [hashicorp/design-system#500]
**Outline the use case for the new icon.**
n/a

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
n/a

**Describe alternatives you've considered.**
n/a

**Screenshots**
n/a

**Figma**
n/a

**Additional context**
An internal ticket has been created for this request.

**Comment by didoo** [comment]
> An internal ticket has been created for this request.
@cveigt can you link to that ticket? thanks

**Comment by cveigt** [comment]
@didoo Here's the Jira [ticket](https://hashicorp.atlassian.net/browse/HDS-447?atlOrigin=eyJpIjoiNzhmMDgyZDdhMGU0NDY1ZGFkYjc5YjU3NjY1M2EzOGYiLCJwIjoiaiJ9).
