### ISSUE TITLE
Bug report: Form::Label::Indicator is only in english

### ISSUE THREAD

**Issue by cbfx** [hashicorp/design-system#502]
## IS: Current behavior
A requirement for components that we implement is that it can change language to the locale the user selects. The `Indicator` component has hard-coded english strings. It will be noted that we should avoid using these args (isRequired, isOptional) and instead opt for the inline badge as a work-around.

https://github.com/hashicorp/design-system/blob/main/packages/components/addon/components/hds/form/indicator/index.hbs

## SHOULD BE: Expected behavior
I am not sure what the expected behavior should be there could be some sort of initialization step that can be re-configured for any language strings used in Hds.

An alternative is to remove the args entirely and enforce Hds::Badge every time.

**Comment by alex-ju** [comment]
Hi @cbfx! We touched on this offline, but leaving a comment for visibility and awareness.

We understand this is not currently a blocker in the adoption of HDS form components in `cloud-ui`, as there are no immediate plans to have the platform in multiple languages, so we captured this in a Jira ticket to investigate localization in the `design-system` repo (more precisely the components package).

**Comment by didoo** [comment]
Moved to https://hashicorp.atlassian.net/browse/HDS-706
