### ISSUE TITLE
Flight icon request: Open Policy Agent (OPA)

### ISSUE THREAD

**Issue by jarrodn-au** [hashicorp/design-system#520]
**Outline the use case for the new icon.**

We are adding Open Policy Agent (OPA) support to Terraform Cloud and would like to display its logo in the Run details page. [RFC](https://docs.google.com/document/d/1kSPJJ5l0psGD0ZDBlaBRKSi1pIbbZwTIqmbKzuMHsms/edit#)

**If there's a similar existing icon, why isn't it a good fit? Please describe.**

There are no similar icons.

**Describe alternatives you've considered.**
N/A

**Screenshots**

WIP Using the `{{inline-svg}}` ember component

<img width="1026" alt="Screen Shot 2022-08-03 at 10 26 15 am" src="https://user-images.githubusercontent.com/7122750/182498851-64eab963-bf1b-49f7-b7ca-0cdb731dba6c.png">

**Figma**

https://www.figma.com/file/euexPgt2fRF2VXUwDOgTMP/Policy-Check-Results-with-Sentinel-and-OPA?node-id=635%3A16113

**Additional context**

The SVG for the icon is https://cncf-branding.netlify.app/projects/opa/

I am currently only using the 'Icon color' variant, but can foresee using the 'Icon black' for other use cases (eg, disabled states)

**Comment by cveigt** [comment]
@jarrodn-au there's a PR opened to add this icon. It'll be available in the next Flight release.
