### ISSUE TITLE
Tweak docs for Card `hasBorder`

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/design-system#572]
Not a bug per se. The Card docs https://design-system-components-hashicorp.vercel.app/components/card say `hasBorder` is a boolean, but it seems like it's intended to be omitted instead of false. 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1372946/190254504-f3cd2308-4c9b-4731-9db3-26680aae08cc.png">

**Comment by didoo** [comment]
@amyrlam I did a quick test, and works as expected:

<img width="1089" alt="screenshot_1780" src="https://user-images.githubusercontent.com/686239/191032932-95bd0026-d6a6-4515-852d-f1677d566d61.png">

What do you think should work (or be documented) differently?

**Comment by amyrlam** [comment]
I should have included a repro, here's what I mean in cloud-ui https://github.com/hashicorp/cloud-ui/pull/3588, maybe it's an issue isolated to there?

**Comment by didoo** [comment]
Ahh,  but with `@hasBorder='false'` in this case `'false'` is a string, not a boolean, so `true` (try to run `!'test'` in a browser's console). The correct way to declare it is `@hasBorder={{false}}` (in this case, using the brackets, we're passing directly the `false` (boolean) value as argument.

**Comment by amyrlam** [comment]
Thanks - gotcha. Yeah maybe the examples on the docs page could say `@hasBorder={{true}}` instead so is clearer?

**Comment by didoo** [comment]
> Yeah maybe the examples on the docs page could say `@hasBorder={{true}}` instead so is clearer?

Opened a PR for this: https://github.com/hashicorp/design-system/pull/575
