### ISSUE TITLE
Bug report: Extra whitespace following an <Hds::Link::Inline> component results in grammatically incorrect sentence structure when followed by punctuation

### ISSUE THREAD

**Issue by efgold** [hashicorp/design-system#669]
## IS: Current behavior

Extra whitespace appears after an `<Hds::Link::Inline>` component such that when links appear in list form, an extra space appears between the link and the comma following it. This is a known issue as described [here](https://ember-twiddle.com/3575bcb7229f8c689339408eb0dcbed2?openFiles=templates.application%5C.hbs%2Ctemplates.components.derived-component%5C.hbs) and [here](https://github.com/hashicorp/design-system/pull/231#issuecomment-1123502499). It was also recently discussed [this Slack thread](https://hashicorp.slack.com/archives/C7KTUHNUS/p1667410562831179). 

Screenshots of bug:
<img width="977" alt="Screen Shot 2022-11-02 at 10 24 06 AM" src="https://user-images.githubusercontent.com/91905706/199578493-75746f97-20df-413f-8aaf-d7f4ed15875a.png">
<img width="753" alt="Screen Shot 2022-11-02 at 10 25 52 AM" src="https://user-images.githubusercontent.com/91905706/199578573-5bb561c8-07a4-4c89-93e4-01a31d2eebd1.png">

The rendered HTML appears like so in the browser inspector:
<img width="617" alt="Screen Shot 2022-11-02 at 10 32 33 AM" src="https://user-images.githubusercontent.com/91905706/199578975-f0558dde-d71f-479e-be9d-3db4b197e008.png">

## SHOULD BE: Expected behavior

Links are able to be formatted in list form without extra whitespace appearing before the punctuation used in the list, for example commas between list items and periods at the end of the list. 

## Steps to reproduce

1. Put <Hds::Link::Inline> components into a handlebars file and separate by comma. When rendered, you will be able to see the extra whitespace applied after the link component. 

## Possible solution

Not known at this time.

**Comment by alex-ju** [comment]
This fix was released in `@hashicorp/design-system-components` v1.3.2 – thank you @efgold for getting us to investigate this!
