### ISSUE TITLE
Issue: `:content` named block in `<Hds::Disclosure>` component lacks appropriate styling

### ISSUE THREAD

**Issue by MelSumner** [hashicorp/design-system#89]
## What happens now

When I put items into both the `:toggle` and `:content` named blocks, the `:content` container does not display over the existing content, but instead shoves the existing content down (which causes the item in the `:toggle` block to jump around). 

## What I expect

When the container is shown, it is shown _over_ other content.

**Comment by didoo** [comment]
As discussed in chat, this is expected. Quoting [the documentation](https://design-system-components-hashicorp.vercel.app/utilities/disclosure) for the `Disclosure`: 

_Important: the "content" is not positioned in any way in relation to the toggle: this responsibility is left to the consumers (eg by applying a `position: absolute` to a wrapper around the content that is passed to the `:content` block)._

**Comment by didoo** [comment]
@MelSumner do you think we can close this one?
