### ISSUE TITLE
Cannot customize "hashicorp-color" icon's fill color

### ISSUE THREAD

**Issue by fivetanley** [hashicorp/design-system#989]
## IS: Current behavior

Given the following code:

```handlebars
<FlightIcon @name="hashicorp-color" @color="white" />
```

I get the following rendering with a _black_ fill always, regardless of what I pass to `@color`:

<img width="609" alt="Screen Shot 2023-01-03 at 12 38 54" src="https://user-images.githubusercontent.com/1275021/210437678-f42761c9-1db8-49ec-86cc-b37f3f068d47.png">

## SHOULD BE: Expected behavior

Should be filled with whatever color is passed into `@color`.

## Steps to reproduce
1. Clone https://github.com/fivetanley/flight-icons-hashicorp-logo-fill-issue
2. run `yarn` and `yarn start`
3. Change values in https://github.com/fivetanley/flight-icons-hashicorp-logo-fill-issue/blob/d071425f51e96c139b3d0b829ffc69b904b42483/app/templates/application.hbs#L4
4. See that the fill color does not change

## Possible solution

I think figuring out a way to remove the [hardcoded `black` value](https://github.com/hashicorp/design-system/blob/2ef95d10c583fb71a2d7fe2c03ef00bbcb874ee4/packages/flight-icons/svg-original/hashicorp-color-16.svg?short_path=df4576c#L4-L6) for the `fill` attribute on the `hashicorp-color` icons could be one way to fix this bug. Since the attributes always take precedence over CSS, it's hard to fix this in consumer-land.

However, it seems possible to work around this by using `hashicorp` instead of `hashicorp-color`, but I guess I'm confused what to use when if that's the case?

**Comment by didoo** [comment]
@fivetanley you are using `@name="hashicorp-color"` you should use `@name="hashicorp"` (the `-color` suffix means to use the icon with the "brand" color which in the HashiCorp case is black)

**Comment by fivetanley** [comment]
@didoo Thanks for the clarification!
